local M = {}

local act = require("wezterm").action

function M.apply_to_config(config)
	local keys = {
		{ key = "Tab", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "Tab", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "Enter", mods = "ALT", action = act.DisableDefaultAssignment },
		{ key = "!", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "!", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = '"', mods = "ALT|CTRL", action = act.DisableDefaultAssignment },
		{ key = '"', mods = "SHIFT|ALT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "#", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "#", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "$", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "$", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "%", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "%", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "%", mods = "ALT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "%", mods = "SHIFT|ALT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "&", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "&", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "'", mods = "SHIFT|ALT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "(", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "(", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = ")", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = ")", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "*", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "*", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "-", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "-", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "-", mods = "CTRL|LEADER", action = act.DisableDefaultAssignment },
		{ key = "0", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "0", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "0", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "1", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "1", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "1", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "2", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "2", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "2", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "3", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "3", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "3", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "4", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "4", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "4", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "5", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "5", mods = "SHIFT|ALT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "5", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "5", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "6", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "6", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "6", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "7", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "7", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "7", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "8", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "8", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "8", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "9", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "9", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "9", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "<", mods = "SHIFT|LEADER", action = act.DisableDefaultAssignment },
		{ key = "<", mods = "SHIFT|CTRL|LEADER", action = act.DisableDefaultAssignment },
		{ key = "=", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "@", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "@", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "L", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "L", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "M", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "M", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "N", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "N", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "P", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "P", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "R", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "R", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "T", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "T", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "U", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "U", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "W", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "W", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "X", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "X", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "Z", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "Z", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "[", mods = "SHIFT|SUPER", action = act.DisableDefaultAssignment },
		{ key = "]", mods = "SHIFT|SUPER", action = act.DisableDefaultAssignment },
		{ key = "^", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "^", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "_", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "_", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "c", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "f", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "f", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "l", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "m", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "m", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "n", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "n", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "n", mods = "LEADER", action = act.DisableDefaultAssignment },
		{ key = "n", mods = "CTRL|LEADER", action = act.DisableDefaultAssignment },
		{ key = "p", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "t", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "t", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "u", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "v", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "w", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "w", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "x", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "z", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "{", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "{", mods = "SHIFT|SUPER", action = act.DisableDefaultAssignment },
		{ key = "}", mods = "SUPER", action = act.DisableDefaultAssignment },
		{ key = "}", mods = "SHIFT|SUPER", action = act.DisableDefaultAssignment },
		{ key = "PageUp", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "PageUp", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },
		{ key = "PageDown", mods = "CTRL", action = act.DisableDefaultAssignment },
		{ key = "PageDown", mods = "SHIFT|CTRL", action = act.DisableDefaultAssignment },

		{ key = "L", mods = "LEADER|CTRL|ALT", action = act.ShowDebugOverlay },
		{ key = "r", mods = "LEADER|CTRL|SHIFT", action = act.ReloadConfiguration },
	}

	if not config.keys then
		config.keys = {}
	end
	for _, key in ipairs(keys) do
		table.insert(config.keys, key)
	end
end

return M
