[colors]
ansi = [
    "#15161e",
    "#f7768e",
    "#9ece6a",
    "#e0af68",
    "#7aa2f7",
    "#bb9af7",
    "#7dcfff",
    "#a9b1d6",
]
background = "#08080b"
brights = [
    "#414868",
    "#f7768e",
    "#9ece6a",
    "#e0af68",
    "#7aa2f7",
    "#bb9af7",
    "#7dcfff",
    "#c0caf5",
]
cursor_bg = "#c0caf5"
cursor_border = "#c0caf5"
cursor_fg = "#08080b"
foreground = "#c0caf5"
selection_bg = "#283457"
selection_fg = "#c0caf5"

[colors.indexed]

[colors.tab_bar]
background = "#191b28"
inactive_tab_edge = "#08080b"

[colors.tab_bar.active_tab]
bg_color = "#08080b"
fg_color = "#7aa2f7"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#08080b"
fg_color = "#545c7e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#08080b"
fg_color = "#7aa2f7"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#191b28"
fg_color = "#7aa2f7"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#7aa2f7"
fg_color = "#08080b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
aliases = []
author = "folke"
name = "Tokyo Night Mod"
origin_url = "https://github.com/folke/tokyonight.nvim"
wezterm_version = "20230712-072601-f4abf8fd"
